spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    platform: postgres
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: rabbitmq
    password: rabbitmq

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT}
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true

maintenance:
  url: ${MAINTENANCE_URL}

rabbit:
  queue-name: confirmationQueue

cleaning:
  rate: ${CLEANING_RATE}
  range: ${CLEANING_RANGE}
