spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: realm-tiw1-tp3
  resource: tp3-client
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true

maintenance:
  url: http://localhost:8080/

rabbit:
    queue-name: confirmationQueue
    url: localhost

cleaning:
  rate: 5000
  range: 60